global:
  scrape_interval:     30s
  evaluation_interval: 30s
  # scrape_timeout is set to the global default (10s).

scrape_configs:
  - job_name: 'rflink'
    static_configs:
      - targets: ['rflink-prom:8080']
#  - job_name: 'node-exporter'
#    static_configs:
#      - targets: ['node-exporter:9100']
